Closes-Bug: issues: #12: Backup/Restore failing for Azure due to VM cid change
cloudfoundry-incubator/service-fabrik-blueprint-service pull request #13
Opened 2017-09-22 02:30 UTC by pritishmishra

Description: Using agent_id instead of cid for instance_id during backup/restore for Azure

2017-09-22 03:28 UTC, pritishmishra commented
This change has been tested and backup/restore functionalities are working fine.

2017-09-22 04:22 UTC, jagadish-kb approved these changes
LGTM

2017-09-24 15:41 UTC, kamath-prasad requested changes

2017-09-24 15:41 UTC, kamath-prasad commented on lib/agent/backuprestore.js
> +    .get(iaasCredentials.name === 'azure' ? 'agent_id' : 'cid')
please update to use new structure of input data here and below.

2017-09-25 03:18 UTC, pritishmishra commented
Modified as per the new changes from the broker's side. Kindly review again.

2017-09-25 04:18 UTC, kamath-prasad approved these changes
LGTM . merging.

2017-09-25 04:18 UTC, merged